In [1]:
#importação de bibliotecas
import numpy as np #np será o apelido

In [2]:
temperaturas = np.array([30,40,50,60,70,90,100])
print(temperaturas)
print(type(temperaturas))

[ 30  40  50  60  70  90 100]
<class 'numpy.ndarray'>

In [3]:
#média aritmética
media = np.mean(temperaturas)
print(media)

62.857142857142854

In [4]:
maior_valor = np.max(temperaturas)
print(maior_valor)

100

In [5]:
menor_valor = np.min(temperaturas)
print(menor_valor)

30

In [6]:
#salários x 1000
salarios = np.array([2,3,4,5,1,500])
media_salarios = np.mean(salarios)
print(media_salarios)
print(f"{media:.2f}")

85.83333333333333
62.86

In [7]:
mediana = np.median(salarios)
print(mediana)

3.5

desafio final:
-criar um array de habitantes de 5 cidades do estado de SP.
-maior população
-menor população
-média de população
-mediana

In [8]:
cidades_do_estado_de_sp= np.array ([1291784,1138309,810.729,748.919,743.432])
maior_populacao = np.max(cidades_do_estado_de_sp)
print(maior_populacao)

1291784.0

In [9]:
menor_populacao = np.min(cidades_do_estado_de_sp)
print(menor_populacao)

743.432

In [10]:
mediana = np.median(cidades_do_estado_de_sp)
print(mediana)

810.729

## Pandas e seaborn

In [11]:
import pandas as pd
import seaborn as sns

In [12]:
df = pd.read_csv(r"C:\Users\FIC\Documents\treinamento_breno\data\dataset_aula02_exercicio_modafina.csv")

In [13]:
df. head()

,data_venda,categoria_produto,tamanho,preco,quantidade,estado,forma_pagamento,nota_avaliacao
0,2024-01-01,Calças,G,177.95,1,SP,Boleto,4.1
1,2024-01-01,Camisetas,G,52.12,1,SP,Cartão,4.3
2,2024-01-03,Calças,G,213.45,3,PR,Pix,3.9
3,2024-01-03,Camisetas,M,76.81,1,RJ,Pix,4.9
4,2024-01-03,Acessórios,M,132.39,2,RS,Pix,2.9

In [14]:
df. shape

(700, 8)

In [15]:
df. describe()

            preco  quantidade  nota_avaliacao
count  700.000000  700.000000      700.000000
mean   168.649329    2.001429        3.980857
std    107.437640    0.808572        0.632392
min     20.380000    1.000000        2.200000
25%     90.222500    1.000000        3.600000
50%    132.640000    2.000000        4.000000
75%    229.255000    3.000000        4.400000
max    499.330000    3.000000        5.000000

In [16]:
df. info()
df. notnull()

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   data_venda         700 non-null    str
 1   categoria_produto  700 non-null    str
 2   tamanho            700 non-null    str
 3   preco              700 non-null    float64
 4   quantidade         700 non-null    int64
 5   estado             700 non-null    str
 6   forma_pagamento    700 non-null    str
 7   nota_avaliacao     700 non-null    float64
dtypes: float64(2), int64(1), str(5)
memory usage: 62.3 KB

,data_venda,categoria_produto,tamanho,preco,quantidade,estado,forma_pagamento,nota_avaliacao
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
695,True,True,True,True,True,True,True,True
696,True,True,True,True,True,True,True,True
697,True,True,True,True,True,True,True,True
698,True,True,True,True,True,True,True,True
699,True,True,True,True,True,True,True,True

In [17]:
df["faturamento"] = df["preco"] * df["quantidade"]